apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-service-config
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  SERVER_PORT: "8761"
  JAVA_OPTS: "-Xms256m -Xmx512m"
  EUREKA_INSTANCE_HOSTNAME: "eureka-service"
  AWS_REGION: "us-east-1"
  AWS_ENDPOINT_URL: ""
