apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-service
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: eureka-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: eureka-service
        app.kubernetes.io/part-of: oficina-platform
    spec:

      containers:
      - name: eureka-service
        image: fiapsoatgrupo36/eureka-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8761
        envFrom:
        - configMapRef:
            name: eureka-service-config
        - secretRef:
            name: eureka-service-secret
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        startupProbe:
          httpGet:
            path: /actuator/health/liveness
            port: http
          failureThreshold: 120
          periodSeconds: 5
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 12
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: http
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 6
